Enhance CI/CD

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -14,7 +14,15 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
-      # 2. Sensor Monitoring BE CI/CD
+      # 2. Debug SSH Connection with Temporary Key File
+      # - name: Debug SSH Connection
+      #   run: |
+      #     echo "${{ secrets.VPS_SSH_KEY }}" > ssh_key
+      #     chmod 600 ssh_key
+      #     ssh -i ssh_key -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "echo Connected!"
+      #   shell: bash
+
+      # 3. Sensor Monitoring BE CI/CD
       - name: Sensor Monitoring BE CI/CD
         uses: appleboy/ssh-action@master
         with:
@@ -23,17 +31,22 @@ jobs:
           key: ${{ secrets.VPS_SSH_KEY }}
           port: 22
           script: |
+            set -e  # Exit immediately if a command exits with a non-zero status
             cd /usr/go/sensor_monitoring_be
             git pull origin master
             go mod tidy
-            pm2 stop sensor_monitoring_be
             go build -o sensor_monitoring_be
-            pm2 start sensor_monitoring_be
+            pm2 restart sensor_monitoring_be
 
-      # 3. Send success notification via custom API
+      # 4. Send success notification via custom API
       - name: Send Telegram Notification
         if: success()
         run: |
           curl -s -X POST https://telebot.apicollection.my.id/api/v1/cicd/send-message \
           -H "Content-Type: application/json" \
           -d '{"message": "✅ Task Succeeded : Monitoring BE Deployed to Production"}'
+
+      # 5. Cleanup
+      - name: Remove SSH Key
+        if: always()
+        run: rm -f ssh_key
